/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.8.3/userguide/multi_project_builds.html
 */

rootProject.name = "otuskotlin-202012-vacancies-sha"

pluginManagement {
    val kotlinVersion: String by settings
    val openapiVersion: String by settings
    val springDependencyVersion: String by settings
    val springBootVersion: String by settings
    val bmuschkoVersion: String by settings
    val kotlessVersion: String by settings

    plugins {
        kotlin("multiplatform") version kotlinVersion
        kotlin("jvm") version kotlinVersion
        kotlin("js") version kotlinVersion
        kotlin("plugin.serialization") version kotlinVersion

        id("org.openapi.generator") version openapiVersion
        id("org.springframework.boot") version springBootVersion
        id("io.spring.dependency-management") version springDependencyVersion
        id("com.bmuschko.docker-java-application") version bmuschkoVersion
        id("io.kotless") version kotlessVersion apply false
    }
}

include("common-be")
include("common-multi")
include("transport-multi")
include("mapper")
