openapi: 3.0.1
info:
  title: Swagger Vacancies
  description: 'Vacancies API'
  version: 0.0.1
servers:
  - url: https://localhost:8080/
  - url: http://localhost:8080/
tags:
  - name: vacancy
    description: Everything about your vacancies
paths:
  /vacancy:
    post:
      tags:
        - vacancy
      summary: Get vacancies
      operationId: getVacancies
      requestBody:
        description: Get vacancies
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetVacancyRq'
        required: true
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVacancyRs'
      x-codegen-request-body-name: body
components:
  schemas:
    GetVacancyRq:
      type: object
      properties:
        rqUid:
          type: string
        rqTm:
          type: string
        ids:
          type: array
          items:
            type: string
    GetVacancyRs:
      type: object
      properties:
        rqUid:
          type: string
        rsUid:
          type: string
        rsTm:
          type: string
        status:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/RsError'
        vacancies:
          type: array
          items:
            $ref: '#/components/schemas/VacancyDto'
    RsError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    VacancyDto:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        specialization:
          type: string
        city:
          type: string
        salary:
          type: string
        description:
          type: string
        experience:
          type: string
        schedule:
          type: string
        manager:
          type: string

